//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpalatorieEntities : DbContext
    {
        public SpalatorieEntities()
            : base("name=SpalatorieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clienti> Clienti { get; set; }
        public virtual DbSet<IstoricProgramari> IstoricProgramari { get; set; }
        public virtual DbSet<Manageri> Manageri { get; set; }
        public virtual DbSet<Muncitori> Muncitori { get; set; }
        public virtual DbSet<Programari> Programari { get; set; }
        public virtual DbSet<ServiciiSpalatorie> ServiciiSpalatorie { get; set; }
    }
}
