//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programari()
        {
            this.IstoricProgramari = new HashSet<IstoricProgramari>();
        }
    
        public int ProgramareID { get; set; }
        public Nullable<int> MuncitorID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int NumarTelefon { get; set; }
        public string NumarInmatriculare { get; set; }
        public string TipulSpalarii { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Ora { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstoricProgramari> IstoricProgramari { get; set; }
        public virtual Muncitori Muncitori { get; set; }
    }
}
