//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciiSpalatorie
    {
        public int TipID { get; set; }
        public string TipSpalare { get; set; }
        public decimal Pret { get; set; }
        public Nullable<decimal> PretRedus { get; set; }
    }
}
